<%@ Control Language="C#" AutoEventWireup="false" CodeFile="HistoryView.ascx.cs" Inherits="wctMain.View.HistoryView" %>
    
<div class="displayer fade fade-slow history-container static-container">
    <div class="section-header">History</div>
    <div class="main-inner">
        <p>Originally constructed in 1926 as the Rialto Theatre, the building at 1135 13th Street had a number of occupants in its early years. The ownership record is nearly as convoluted as the list of business occupants. The property was sold in April 1926 by William Beach to Adrian G. Diez, who constructed the building. He sold it in May 1927 to the Curran-Isis Theatres Company (Frank Ricketson and associates). They sold in 1930 to the Fox Colorado Theatre Group, who in turn sold it in 1933 to the Fox Colorado Theatre Company. A quitclaim deed in 1935 resulted with the Boulder K & F Realty Company as the new owner. They sold it in 1946 to the Isis Theatre Company (also Fox Intermountain Theaters). County Assessor’s records are not available until a transaction in 1978, when the building was sold by the National General Theaters to the Mann Theaters Corporation. This company sold the property in 1988 to Cinamerica Theaters. In 1994, the present owner, Celtic Properties, purchased the building at 1135 13th Street.</p>
        <p>Recent newspaper articles state that the Rialto was originally a vaudeville theater, but earlier newspaper reports seem to indicate that it was a movie theater. After Diez sold the Rialto to the Curran-Isis Theatres Company, they operated it for only a few months before it “closed for lack of business.” It is possible that the Rialto was purchased and closed down so as not to compete with the other entertainment theaters operated by the group, which included the Isis, or that vaudeville theaters had reached the end of their usefulness. By 1932, the building was still listed in the city directories as “vacant.”</p>
        <p>In 1938, Buffalo Club Dancing occupied the building, and was there through at least 1940, but in 1943, the building was again vacant. That year, another business started up. The Anchorage opened on April 9, 1943 (although the Boulder Daily Camera article lists the address as 1155 13th Street). The manager, John Hart, had been rejected for military service and turned his attention to developing a recreation center on University Hill for students, sailors, and townspeople. Hart states, “I have been encouraged to open the building as a club by persons who recognize the shortage of entertainment places in Boulder. There has been an increasing demand since the destruction of Canon Park. I intend to run a first class place and although I have been handicapped in getting ready for the opening through an inability to get sufficient help, The Anchorage will be ready for the opening.”</p>
        <p>Music for dancing was provided every Friday and Saturday night, and jukeboxes located in the balcony provided music for dancing on other occasions. Just four months later, however, City Manger H.C. McClintock closed the Anchorage, referred to as a “soft drink and dancing place,” for a week as a penalty for a liquor party. Referred to variously as the Anchorage Bar & Grill, it was located here at least through 1949.</p>
        <p>When Fox Intermountain purchased the building in 1946, there was initially discussion of converting the building back into a theater. Those plans never materialized, however, and a building permit was issued to the Fox Theatre Company in 1951 to remodel the building into a cafeteria. Although an advertisement in the Daily Camera noted that Ted’s Buff Café & Cafeteria was opening on November 9, 1954, it appeared in the city directories in 1953. The Buff Café was advertised as “Boulder’s most modern eating house.” It operated from 6:30 a.m. to 1:30 p.m., and re-opened in the afternoon from 4:30 p.m. to 7:00 p.m.</p>
        <p>The Fox Theater, located at 2022 14th Street in downtown Boulder, was destroyed by fire on April 18, 1960. In July of that year, the Fox Intermountain Amusement Corporation applied for a permit to remodel the subject building into a movie theater. They had been denied a permit to erect a 373-square-foot (34.7 m2) marquee, but reapplied for a 230-square-foot (21 m2) marquee. A sign permit application was filed for the Fox Theatre by Boulder Sign Ideas in January 1961. The plans included the “Fox” sign, as well as the lighted marquee. The marquee was 42’ 8” wide, 5’ tall, and 51/2’ wide at the base. The new Fox Theatre was opened on July 7, 1961. Present at the formal opening was the president of Fox Inter-Mountain Theatres, Robert Selig. Besides the sign and metal screen covering the front façade, another alteration to the building at this time was the installation of a 36 x 18’ screen which was “designed to accommodate all sizes of motion pictures, including the spectacular cinemascope process, developed by 20th Century Fox.” The Theatre was designed by Mel Glatz, Fox construction engineer, and assisted by Les Newkirk, the manager of Fox Theatres in Boulder. There were 500 seats for persons, with the arrangement assuring “each patron spacious leg room between the American Bodiform chairs.” A stereophonic sound system, new lobby with concession stand, specially built cooling system, and new rest rooms rounded out the changes to the building. For the opening night, only one show was scheduled, but afterwards it operated on continuous showings beginning at 1:30pm.</p>
        <p>In 1991, the Pyramid Group, Inc. leased the building from the Mann Theatres and received a liquor license from the City, with plans to turn the building into a concert hall. The interior of the building was altered for new use, providing for a sellable capacity of 625 people. The music hall focused on national concerts.</p>
        <p>The addresses for all of the businesses located in the building have varied from 1133 through 1141 13th Street. When the building was first constructed in 1926, it also included two small shops, which flanked the central entrance to the theater. In 1936, Al’s Shine Parlor was one of the enterprises that were located in these smaller shops throughout the years. Other smaller businesses have included: Albert D’ Elai, Barber and Penny Arcade in 1956; D’ Elai and Security Mutual Life Insurance in 1959; Buff’s Shoe Shop in 1966; Boulder’s House of Flowers in 1969; and Door of Perception Electronic Equipment and Carousel Beauty Salon in 1972.</p>
    </div>
</div>
